### ISSUE TITLE
Swipe/Touch Actions for playing games

### ISSUE THREAD

**Issue by ALTAMASH93** [lukasroegner/homebridge-apple-tv-remote#101]
Hello Lukas,

Fantastic Work. Just wanted to know if there is a way we can send touch or swipe events, similar to the way it can be sent from the physical remote? Trying to play games, as soon as the game launches the left/right buttons don't work.

Best Regards,
Altamash Ahmad

**Comment by lukasroegner** [comment]
That won't work. The latency if the communication is way too slow to play games. Swiping is also not supported, only "button" presses can be sent via the API.
