### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by Willygoat1** [lukasroegner/homebridge-apple-tv-remote#109]
I'm getting a permission denied error when running npm install -g node-appletv-x

**Comment by Willygoat1** [comment]
hoobs@hoobs:~ $ npm install -g node-appletv-x
npm ERR! code EACCES
npm ERR! syscall rename
npm ERR! path /usr/lib/node_modules/node-appletv-x
npm ERR! dest /usr/lib/node_modules/.node-appletv-x-4I2HQjWj
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, rename '/usr/lib/node_modules/node-appletv-x' -> '/usr/lib/node_modules/.node-appletv-x-4I2HQjWj'
npm ERR!  [Error: EACCES: permission denied, rename '/usr/lib/node_modules/node-appletv-x' -> '/usr/lib/node_modules/.node-appletv-x-4I2HQjWj'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'rename',
npm ERR!   path: '/usr/lib/node_modules/node-appletv-x',
npm ERR!   dest: '/usr/lib/node_modules/.node-appletv-x-4I2HQjWj'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hoobs/.npm/_logs/2021-08-01T01_09_33_419Z-debug.log
hoobs@hoobs:~ $ npm install -g node-appletv-x

npm ERR! code EACCES
npm ERR! syscall rename
npm ERR! path /usr/lib/node_modules/node-appletv-x
npm ERR! dest /usr/lib/node_modules/.node-appletv-x-4I2HQjWj
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, rename '/usr/lib/node_modules/node-appletv-x' -> '/usr/lib/node_modules/.node-appletv-x-4I2HQjWj'
npm ERR!  [Error: EACCES: permission denied, rename '/usr/lib/node_modules/node-appletv-x' -> '/usr/lib/node_modules/.node-appletv-x-4I2HQjWj'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'rename',
npm ERR!   path: '/usr/lib/node_modules/node-appletv-x',
npm ERR!   dest: '/usr/lib/node_modules/.node-appletv-x-4I2HQjWj'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hoobs/.npm/_logs/2021-08-01T01_10_41_491Z-debug.log

**Comment by Christian-CFP** [comment]
> I'm getting a permission denied error when running npm install -g node-appletv-x
> 
> 

You have to run this with sudo:

sudo npm install -g node-appletv-x

**Comment by Willygoat1** [comment]
Thank you.
