### ISSUE TITLE
Feature Request: Persist option

### ISSUE THREAD

**Issue by Nastras** [lukasroegner/homebridge-apple-tv-remote#13]
Hello, Lukas,

I noticed one other little thing about the Apple TV Plugin.

I have a maintenance script running at night that restarts all control centers and also the Pi.
After running this script, the Apple TV is on without TV, after that the Pi is restarted.

Here it looks like that after restarting the Pi the plugin detects that Apple TV is on and sends the power command again. This will also switch on the TV.

Can you build in a protection that the TV is not turned on? Maybe a persist status for the power switch?

Thank you!

Regards 
Nastra

**Comment by lukasroegner** [comment]
Hi @Nastras,

This seems to be a bug, the state of the switch is persisted by homebridge, the Apple TV should never be automatically switched on by the plugin. Is this issue still existing in the `next` version?

**Comment by Nastras** [comment]
Hey ho,
just tested. The error does not occur anymore with the next version!

Thanks!!!

**Comment by Nastras** [comment]
Hi, Luke,
i noticed in the current version that the error is again present.

If the Apple TV is restarted at night via a power reset then the plugin switches the switch to true and the connected TV goes on via hdmi cec.

Could you check again?

![191BBB88-2D5F-4334-A711-8F0FBA946C32](https://user-images.githubusercontent.com/27686185/77813359-4bfe6000-70a8-11ea-8d08-78c0f1d76a9a.jpeg)

**Comment by lukasroegner** [comment]
I don't think that it is the same bug. The logs show that your custom switch toggled 30 seconds after initialization. Do you have an automation running?

**Comment by Nastras** [comment]
Yes, I have also noticed that I have not yet managed to complete my description. It occurs at the dashboard switch. This is connected to an automation and restarts a certain app after the start of the apple tv.

Is it possible that you can add a persist protection for the additional switches to avoid this?

**Comment by lukasroegner** [comment]
The command switches cannot be persisted, as they are stateless. Can you explain your automation in detail? Maybe, you just have to tweak it.

**Comment by Nastras** [comment]
The trigger for the dashboard switch is always triggered when the apple tv is switched on and once every hour.

Condition is that the Apple TV is turned on.

![EB82484E-2BCF-4E33-84F8-BAA4123AACA9](https://user-images.githubusercontent.com/27686185/77817721-8f1efa00-70cd-11ea-9f3b-11e71d28e1c5.jpeg)
![F678DC27-AAA6-4962-AAEE-4FC2CE8BEA78](https://user-images.githubusercontent.com/27686185/77817722-92b28100-70cd-11ea-8bf8-4105d5acef61.jpeg)
![42088F73-C623-46D8-81AD-4B7811E642AA](https://user-images.githubusercontent.com/27686185/77817723-934b1780-70cd-11ea-9879-37989c9f9fbf.jpeg)

BTW has your Moodo actually arrived?

**Comment by lukasroegner** [comment]
I don't see an issue. Could you add the `-D` parameter to this homebridge instance? The detailed logs might help to find the issue.

The automation should not have started, as (I assume) the Apple TV has not been powered on.

**Comment by Nastras** [comment]
The background is that I use the app dayview on my smart mirror to display a dashboard with homekit camera image. Unfortunately the camera image freezes from time to time. Therefore the app has to be restarted regularly.

So if you have an idea would be great?

https://forum.smartapfel.de/forum/thread/389-smartmirror-magicmirror-selber-bauen/?postID=68795#post68795

**Comment by Nastras** [comment]
I just tried it, after every power on and off the dashboard switch is triggered.
I attached the log to you.
[log.txt](https://github.com/lukasroegner/homebridge-apple-tv-remote/files/4396783/log.txt)

**Comment by Nastras** [comment]
I had previously implemented it using the play switch and connected it to a shortcut ssh so the problem did not occur.

**Comment by lukasroegner** [comment]
> I just tried it, after every power on and off the dashboard switch is triggered and this will launch Apple TV.

Ok, so 
- the Apple TV is off
- the homebridge instance is restarted
- the Dashboard switch is switched to On (which it should not do)

is that correct?

**Comment by Nastras** [comment]
Yes👍

**Comment by lukasroegner** [comment]
The logs also show that the switch is actually set to ON by the automation.

If you power off the Apple TV manually, does it also restart (i.e. is the automation triggered)?

**Comment by Nastras** [comment]
If I restart it via the plug with power cycle then the automation is triggered. So I produced the log from above.
If I switch it off via your plugin in homekit or via the apple tv itself then not.

So only with the power cycle the automation is triggered.

**Comment by lukasroegner** [comment]
Power cycle means that you disconnect the Apple TV physically from AC, e.g. by pulling the plugin or via a smart plug, is that correct?

**Comment by Nastras** [comment]
I'm just testing it again in 5 min .-)

**Comment by Nastras** [comment]
Is it possible that the persist state is twisted?

**Comment by Nastras** [comment]
![1A49FDCF-EB50-4ECA-BD89-57470B2ACF62](https://user-images.githubusercontent.com/27686185/77822015-2b0d2d80-70ef-11ea-9af9-baf3fcbee3ae.jpeg)
I have now tested it again. The first time it behaved as described above, the second time the behavior was normal.

![0093980D-F5F6-4391-A5FB-F4CAC61154A6](https://user-images.githubusercontent.com/27686185/77822011-26e11000-70ef-11ea-9a32-4593e0c1056f.jpeg)

> Power cycle means that you disconnect the Apple TV physically from AC, e.g. by pulling the plugin or via a smart plug, is that correct?

Yes from AC with Smart Plug.

**Comment by lukasroegner** [comment]
> Is it possible that the persist state is twisted?

Do you mean persisting the On/Off state of the Apple TV in HomeKit? This persistence is handled by homebridge, not some custom code that I wrote.

**Comment by lukasroegner** [comment]
> Yes from AC with Smart Plug.

I assume that the Apple TV is "on" for a short time when booting. That short "on" time is registered by the plugin, thus the automation is triggered.

**Comment by Nastras** [comment]
That's exactly what it will be. Just retested it.

Plugin stopped.
Apple Tv separated from AC
Plugging started 

This time he didn't release the shutter but he did switch the switch from Apple TV to on. This switch also stays on because the apple tv only goes into standby after a certain time.

**Comment by Nastras** [comment]
Do you have an idea for a Workaround?

**Comment by lukasroegner** [comment]
Not really...the plugin cannot detect a restart of the Apple TV via AC off.
Why do you restart the Apple TV via unplugging AC?

**Comment by Nastras** [comment]
Because it serves as a home hub and I have found that an AC reset every 24 hours improves reliability.

But I will now deactivate this Apple TV as a home hub and exclude it from ac reset.

I will tell you tomorrow if it has reappeared 😉

Thank you for the support and have a nice saturday!

**Comment by Nastras** [comment]
So after 24 hours of testing I find that the problem only occurs when you do an AC reset. So the plugin can't help it and I close down.

Thanks Luke!
