### ISSUE TITLE
Feature Request - Add device name to button name

### ISSUE THREAD

**Issue by NorthernMan54** [lukasroegner/homebridge-apple-tv-remote#19]
I have a user of my homebridge-alexa plugin that is using your plugin and are having an issue caused by duplicate device names.  This is due to using the same device name on multiple accessories, and Alexa having issues with duplicate names.

To workaround this, is it possible to implement an option like this from the other Apple TV Plugin?

"defaultSwitchesIncludeATVName": false

And if enabled add the device name to the button name ie Play ( Family Room )

Tks

**Comment by lukasroegner** [comment]
Could be implemented...but the user can just rename the accessory and the services in the Home app, wouldn't that be easier???

**Comment by NorthernMan54** [comment]
Unfortunately renaming in the Home app does not work, as the name change is done within the home app and not published back to homebridge.

**Comment by johnlietzke** [comment]
Work arounds you can think of for the duplicate name that NorthernMan54 mentions?

**Comment by NorthernMan54** [comment]
Would you be open for a pull request with this enhancement?

**Comment by johnlietzke** [comment]
Sure.  Thank you. Please send me any information about the pull request.

**Comment by lukasroegner** [comment]
I added two settings for the initial names of the switches (`onOffSwitchName` and `playPauseSwitchName`), so that you have full control over the name that you want to use with Alexa.

**Comment by johnlietzke** [comment]
Thank you.  I looked over your repository for a minutes before dinner and was going to try and fork a solution tomorrow.  

Thank you again.

**Comment by NorthernMan54** [comment]
Tks @lukasroegner very much appreciated
