### ISSUE TITLE
Permission issues with installing node-appletv-x

### ISSUE THREAD

**Issue by atravis62** [lukasroegner/homebridge-apple-tv-remote#24]
Im totally new at this so please forgive me but could you help me out trying to allow permission so i can install node-appletv-x? I attached the error i keep getting. 
Thannk you.

pi@raspberrypi:~ $ npm install -g node-appletv-x
npm WARN checkPermissions Missing write access to /usr/lib/node_modules
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/lib/node_modules
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/usr/lib/node_modules'
npm ERR!  [Error: EACCES: permission denied, access '/usr/lib/node_modules'] {
npm ERR!   stack: "Error: EACCES: permission denied, access '/usr/lib/node_modules'",
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/lib/node_modules'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-04-17T16_39_20_134Z-debug.log

**Comment by lukasroegner** [comment]
There are many blog posts and tutorials on the internet on how to solve permission issues with node in Linux. I would suggest to try with `sudo` at first.

**Comment by atravis62** [comment]
That was it, thank you. I have a lot more learning to do
