### ISSUE TITLE
Sleep Off auto vs sleep Off automatisation

### ISSUE THREAD

**Issue by j3r3m067** [lukasroegner/homebridge-apple-tv-remote#26]
Hello,
I installed your plugin previous week, but when my Apple TV sleep Off automatically, and I execute an automatisation script (that puts my Apple TV to sleep + more actions) the plugin turns the Apple TV back on.
The script is based on the cache and not on the actual state of the device.
Thanks

**Comment by matcik890** [comment]
I have a similar problem. When you turn off apple tv, it turns on again, and the switch position in the home kit does not match the tv status.

**Comment by lukasroegner** [comment]
The On/Off switch for the Apple TV works by emulating remote keys.

On: press on TV button
Off: long press on TV button, then press on select button

Automations trigger a change to the target state even if the device is already in the target state. I've published a new version (`0.7.6`) that prevents executing the the action if it is already in the target state. Please check whether this new version works for you.

**Comment by j3r3m067** [comment]
Thanks

**Comment by j3r3m067** [comment]
The problem seems to be solved.  I might be back in a few days to confirm it.

**Comment by lukasroegner** [comment]
Ok, feel free to reopen the issue!

**Comment by j3r3m067** [comment]
The problem is reproducible again, did you change something?
