### ISSUE TITLE
Switch State

### ISSUE THREAD

**Issue by koupus** [lukasroegner/homebridge-apple-tv-remote#27]
Hello Lukas,
First, thanks for your great work.
One question:
The state of the switch on my apple tv goes back to on after turning it off.  This ATV serves as a homekit concentrator.  Will his status never be off? Or is there a bug? 
I have a second ATV and the switch work fine (not use as concentrator at this time).
Thanks for your answer, bye.
Tom

**Comment by lukasroegner** [comment]
Hi @koupus,
Can you start homebridge in debug mode (parameter `-D`) and provide the logs for this event (you switch the Apple TV off, the switch goes back to on)?

Thank you!

**Comment by koupus** [comment]
Hi Lukas,
Seems to be Ok right now, I just reboot the ATV.
Sorry for disturb.
Thanks, Tom.
