### ISSUE TITLE
No Apple TVs found on the network. Try again.

### ISSUE THREAD

**Issue by jwa1d62** [lukasroegner/homebridge-apple-tv-remote#29]
Hi -
Apple TV 4k is at 192.168.1.254, but is not found.
Running on Windows 10.
I googled the message and 2 hits came up for this project, but I could not resolve after reading thru.
- Many thanks -

C:\Windows\System32>appletv pair
	No Apple TVs found on the network. Try again.

C:\Windows\System32>ping 192.168.1.254

	Pinging 192.168.1.254 with 32 bytes of data:
	Reply from 192.168.1.254: bytes=32 time=8ms TTL=64
	Reply from 192.168.1.254: bytes=32 time=4ms TTL=64
	Reply from 192.168.1.254: bytes=32 time=6ms TTL=64
	Reply from 192.168.1.254: bytes=32 time=6ms TTL=64

	Ping statistics for 192.168.1.254:
	Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
	Approximate round trip times in milli-seconds:
	Minimum = 4ms, Maximum = 8ms, Average = 6ms

C:\Windows\System32>npm -version
	6.13.4

**Comment by lukasroegner** [comment]
Are you sure that the IP address of the Apple TV is actually `192.168.1.254`? It looks to me as if this IP address is the one of the gateway, not the Apple TV itself. Can you check that in the network setting on the Apple TV just to make sure this is not the issue?

**Comment by jwa1d62** [comment]
I, too, thought that IP address (chosen by DHCP) looked odd.

To start clean, I factory reset my AppleTV and set it up again. 254 was chosen again by DHCP, and all works (as it did before), but 'appletv pair' still times out, no apple tv found.

Would you recommend me setting up the network manually on the Apple TV, and selecting an unused port, say 250, for instance ?

Thank you for your help!

![IMG_0598(1)](https://user-images.githubusercontent.com/53238866/80139239-23b53480-8574-11ea-9a7d-b14b8b0eebcb.jpg)

**Comment by lukasroegner** [comment]
Can you try the appletv pair command with firewall temporarily turned off? Maybe the firewall prevents the tool to communicate with the AppleTV

**Comment by jwa1d62** [comment]
I  turned off the only firewall I know of, and got the same timeout.

![2020-04-23_15-19-29](https://user-images.githubusercontent.com/53238866/80140576-26188e00-8576-11ea-9d89-366398b0ba59.png)

**Comment by lukasroegner** [comment]
Maybe the `appletv pair` command does not work as expected on Windows. Do you have a Unix-based system (macOS, Linux, maybe a Raspberry Pi)?

**Comment by jwa1d62** [comment]
Not currently, unfortunately. I have used rPi's before, but currently run HomeBridge on an always-on Win 10 box.  So, I suppose we can close this - thank you for the timely responses & suggestions!

**Comment by lavigha98** [comment]
> Maybe the `appletv pair` command does not work as expected on Windows. Do you have a Unix-based system (macOS, Linux, maybe a Raspberry Pi)?

Yes it seems this way - I can see the Apple TV's on my Mac but not on the windows server where HomeBridge is running.
