### ISSUE TITLE
Any affect to this plugin from the latest Homebridge update?

### ISSUE THREAD

**Issue by lukebrannon1** [lukasroegner/homebridge-apple-tv-remote#34]
Hi there, just curious if any of the changes related to Apple TV listed under "Notable Changes" of v1.0 at the link below have any positive or negative impact on the homebridge-apple-tv-remote plugin? Specifically, I sometimes the on/off state or play/pause state stuck or incorrect due to what I understand as limitations with the data available. Just curious if any of the changes listed on the new release might help that. 

https://github.com/homebridge/homebridge/releases

**Comment by lukasroegner** [comment]
Hi @lukebrannon1, homebridge 1.0.0 does not help with the actual issue that the data coming from the Apple TV is not accurate. For the on/off state, there seems to be a better solution, which you can test on the `beta` branch. See #30 for details.
