### ISSUE TITLE
API say ok but don’t work

### ISSUE THREAD

**Issue by italoc** [lukasroegner/homebridge-apple-tv-remote#35]
I’m trying API system with Siri shortcut, shortcut say OK but nothing happen

I use this JSON for test 
`{"commands":[{"key":"topmenu"}]} `

P.s:there is a way to run specific app from API (example run with unique ID com.app.test ?

**Comment by lukasroegner** [comment]
Siri shortcuts already provide native support to switch the Apple TV on/off and start a specific app.

The API of this plugin is helpful when you want to control the Apple TV via HomeKit Automations.
I use the SSH action in HomeKit Automations to switch the Apple TV on:
```
curl -X POST 'http://localhost:40000/bedroom' -H 'Authorization: mysecrettoken' -H 'Content-Type: application/json' --data-raw '{"commands":[{"key":"topmenu"}]}'
```

**Comment by italoc** [comment]
> Siri shortcuts already provide native support to switch the Apple TV on/off and start a specific app.
> 

In tvOS 13 the method http://appletvip:3689/login?pairing-guid=SerialNumber# seems to be broken and don’t work, you know another method for start a specific app?

**Comment by italoc** [comment]
Sorry I have found the native option in shortcuts

Thanks
