### ISSUE TITLE
volumeup and volumedown not funcitonal

### ISSUE THREAD

**Issue by zany92** [lukasroegner/homebridge-apple-tv-remote#39]
Thank you for this great plugin.

I tried to use volumeup volumedown command without any result.
All other commands works fine except those ones.
Did I missed something?

**Comment by lukasroegner** [comment]
How is your hardware configuration? I think that volume up/down only work if your audio setup is controlled via HDMI CEC.

**Comment by zany92** [comment]
Thank Lukas. HDMI CEC. Works well with the physical remote but no way to make it works. Tried short and long press without success. The switch toggle but nothing append.

BTW, do you plan to implement the volume command in the future? I have a IR control video projector paired with another AppleTV. Volume is controlled by IR and it works great. Would be awesome to be able to use Homebridge plugin.

**Comment by lukasroegner** [comment]
@zany92 I only have Sonos PlayBars attached to the TVs, those are controlled via IR, which means I cannot check CEC. What I have done to test whether the commands are transmitted properly is to go into the AirPlay settings. There I chose output to an AirPlay 2 device. In this AirPlay view, if the focus is on a device, a message appears that you can change the volume of the AirPlay device with the volume up/volume down button on the remote. If I'm in this view, and the AirPlay device is focused, I can send volumeup/volumedown commands to actually control the volume of the AirPlay device, which means that commands are successfully transmitted to the Apple TV.

I assume that the volume commands only work in a specific hardware configuration, however, I thought that HDMI CEC should be supported...maybe it is not.

**Comment by zany92** [comment]
Thank you. I will try as described and let you know if it works.

Do you plan to add a light dimmer command for volume control, that would be more convenient than triggering volumeup/volumedown ?
thanks

**Comment by lukasroegner** [comment]
@zany92 I'm not planning to add more controls to the plugin, at least for now. As soon as Apple adds an appropriate device category, I'm willing to integrate more features.

Feel free to fork the plugin, I accept PRs for new features. If you need a short intro on how to debug and build the plugin, see #36.

**Comment by zany92** [comment]
Thank you Lukas
