### ISSUE TITLE
can't find an apple tv...vA1469 (Apple TV 3)

### ISSUE THREAD

**Issue by MaksimChikulin** [lukasroegner/homebridge-apple-tv-remote#40]
![6CC4AC20-E9DD-47AA-8E4B-8752B96237E0](https://user-images.githubusercontent.com/63538603/81502670-b4bc3780-92f8-11ea-9b92-16ee6c49ebe1.png)
This model is supported?

**Comment by lukasroegner** [comment]
I'm sorry, the Apple TV 3 and lower are not supported. I'll update the README, I thought I mentioned the supported models, but apparently, I haven't.

**Comment by MaksimChikulin** [comment]
Thanks for information, try to control with some IR plug in)
