### ISSUE TITLE
High CPU usage after 12-24 hour runtime

### ISSUE THREAD

**Issue by andrewturko** [lukasroegner/homebridge-apple-tv-remote#45]
CPU usage climbs after running plugin for more than 12 hours, up to 40% continuous usage, slowing down system to eventual non-functioning state on RBP 4. Restart is only resolution.

**Comment by lukasroegner** [comment]
Stability issues (see #46) might be the cause of your problem, I'll take a look at the CPU usage during extensive testing.

**Comment by Aekung** [comment]
I used to have a cpu spike for few minutes after restarting the homebridge server on the previous version of the plugin but with the newest version, the cpu spike will never go down once and it hung up my homebridge network that I have to temporary uninstall the plugin for now.

Please kindly look into this. I really love the plugin.

**Comment by lukasroegner** [comment]
High CPU issue now tracked in #46.
