### ISSUE TITLE
Problem with commands

### ISSUE THREAD

**Issue by adamrzanek** [lukasroegner/homebridge-apple-tv-remote#48]
I know that the plugin isn’t stable. What I want to report is that sometimes commandswitches doesn’t work until I reboot homebridge. I’m only using those to wake up and putting Apple TV to sleep in automations.

**Comment by lukasroegner** [comment]
If you only use them in automations, you should really switch to the HTTP API and not expose switches to HomeKit.

If switches are exposed to HomeKit, the connection to the Apple TV has to left open, which results in stability issues. If you only use the HTTP API, the connection is established, commands are sent and connection is closed.

Just use the SSH or HTTP action in the HomeKit automations to call the HTTP API.

**Comment by adamrzanek** [comment]
Thanks I will try this. To be honest I’m using it mainly to to wake and sleep Apple TV with hue sync tv accessory :)

**Comment by adamrzanek** [comment]
I want to add that switches are becoming useless exactly at midnight

**Comment by adamrzanek** [comment]
Ok, maybe i’m to noob to do this. But i totally don’t know how to get an api :(

**Comment by adamrzanek** [comment]
@lukasroegner Any idea why? i have thi status?

**Comment by lukasroegner** [comment]
You have to enable the API of the plugin, i.e. set the following values in the config:
```
isApiEnabled: true,
apiPort: 40304,
apiToken: 'my-secret'
```

Now, the API is enabled and reachable at `http://<YOUR-HOST-IP-ADDRESS>:40304`. Read through the "API" section of the README to understand how to use it.

**Comment by lukasroegner** [comment]
I'm closing this for now, feel free to re-open if you have further issues regarding the commands.
