### ISSUE TITLE
Installation failled

### ISSUE THREAD

**Issue by Matcha42eu** [lukasroegner/homebridge-apple-tv-remote#49]
Just to let you know:

`pi@homebridge:/var/lib/homebridge $ npm install -g homebridge-apple-tv-remote
npm ERR! prepareGitDep 1> 
npm ERR! prepareGitDep > spawn-sync@1.0.15 postinstall /home/pi/.npm/_cacache/tmp/git-clone-9c0f0fe3/node_modules/spawn-sync
npm ERR! prepareGitDep > node postinstall
npm ERR! prepareGitDep 
npm ERR! prepareGitDep 
npm ERR! prepareGitDep > protobufjs@6.9.0 postinstall /home/pi/.npm/_cacache/tmp/git-clone-9c0f0fe3/node_modules/protobufjs
npm ERR! prepareGitDep > node scripts/postinstall
npm ERR! prepareGitDep 
npm ERR! prepareGitDep 
npm ERR! prepareGitDep > node-appletv-x@1.0.18 prepare /home/pi/.npm/_cacache/tmp/git-clone-9c0f0fe3
npm ERR! prepareGitDep > npm run build
npm ERR! prepareGitDep 
npm ERR! prepareGitDep 
npm ERR! prepareGitDep > node-appletv-x@1.0.18 build /home/pi/.npm/_cacache/tmp/git-clone-9c0f0fe3
npm ERR! prepareGitDep > npm run clean
npm ERR! prepareGitDep 
npm ERR! prepareGitDep 
npm ERR! prepareGitDep 2> npm WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead.
npm ERR! prepareGitDep npm WARN deprecated @types/ora@3.2.0: This is a stub types definition. ora provides its own type definitions, so you do not need this installed.
npm ERR! prepareGitDep npm ERR! missing script: clean
npm ERR! prepareGitDep 
npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:
npm ERR! prepareGitDep npm ERR!     /home/pi/.npm/_logs/2020-06-21T09_42_16_303Z-debug.log
npm ERR! prepareGitDep npm ERR! code ELIFECYCLE
npm ERR! prepareGitDep npm ERR! errno 1
npm ERR! prepareGitDep npm ERR! node-appletv-x@1.0.18 build: `npm run clean`
npm ERR! prepareGitDep npm ERR! Exit status 1
npm ERR! prepareGitDep npm ERR! 
npm ERR! prepareGitDep npm ERR! Failed at the node-appletv-x@1.0.18 build script.
npm ERR! prepareGitDep npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! prepareGitDep 
npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:
npm ERR! prepareGitDep npm ERR!     /home/pi/.npm/_logs/2020-06-21T09_42_16_329Z-debug.log
npm ERR! prepareGitDep npm ERR! code ELIFECYCLE
npm ERR! prepareGitDep npm ERR! errno 1
npm ERR! prepareGitDep npm ERR! node-appletv-x@1.0.18 prepare: `npm run build`
npm ERR! prepareGitDep npm ERR! Exit status 1
npm ERR! prepareGitDep npm ERR! 
npm ERR! prepareGitDep npm ERR! Failed at the node-appletv-x@1.0.18 prepare script.
npm ERR! prepareGitDep npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! prepareGitDep 
npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:
npm ERR! prepareGitDep npm ERR!     /home/pi/.npm/_logs/2020-06-21T09_42_16_411Z-debug.log
npm ERR! prepareGitDep 
npm ERR! premature close

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-06-21T09_42_16_571Z-debug.log`

**Comment by esgie** [comment]
Same here.
Node 12.8.1.
No script „clean” in dev’s node-apple-tv-x fork installation script or something.
hope for a quick fix

**Comment by esgie** [comment]
For me workaround was to install as root, e.g. by logging as root:
su root
<enter password>
sudo npm install -g —unsafe-perm homebridge-apple-tv-remote

I wasn’t able to install as a pi user, even by sudo.

**Comment by andrewturko** [comment]
Yesterday’s update completely broke plugin for me, with server error. Unsure if related to this.

**Comment by lukasroegner** [comment]
This issue occurred due to a git-based dependency. The latest version 0.8.7 doesn't have that dependency, so installation should succeed.
