### ISSUE TITLE
[Feature Request] Expose as TV Accessory

### ISSUE THREAD

**Issue by malmentm** [lukasroegner/homebridge-apple-tv-remote#51]
Would it be possible to expose the Apple TV on/off switch as a TV Accessory?

**Comment by lukasroegner** [comment]
Technically, it's possible. I'll focus on the stability issues first.

**Comment by malmentm** [comment]
Make it a TV Accessory would help a great deal when i use Google home to power on the Apple TV through home bridge :)

**Comment by johnlietzke** [comment]
It would be really nice to add the Apple TV as a TV accessory for automation.  A switch is good but TV is more intuitive for the non Homebridge oriented people in the household.

**Comment by maxphour** [comment]
Don't know how it works, but would be nice to expose the plugin as a set top box in HomeKit. It's new in iOS 14.

**Comment by johnlietzke** [comment]
I saw this on another Apple TV plugin ### https://github.com/kurtwarwick-new/homebridge-appletv-now-playing/issues. Making the Apple TV as a TV or set top box as discussed in the Issues would make it easier for users to find in Homekit.

**Comment by lukasroegner** [comment]
Latest version 0.10.0 supports adding it as a TV accessory with Apple TV icon.
