### ISSUE TITLE
Failed to update to newer version from Config UX or command line

### ISSUE THREAD

**Issue by robboz4** [lukasroegner/homebridge-apple-tv-remote#52]
From the log:

251 error Command failed: git clone --mirror -q https://github.com/lukasroegner/node-appletv-x.git /root/.npm/_cacache/tmp/git-clone-bf6d70d0/.git
251 error fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-bf6d70d0/.git'
252 verbose exit [ 1, true ]

Tried sunning standalone as su :

pi@Homebridge:/var/homebridge $ sudo npm install homebridge-apple-tv-remote@latest
npm ERR! code 128
npm ERR! Command failed: git clone --mirror -q https://github.com/lukasroegner/node-appletv-x.git /root/.npm/_cacache/tmp/git-clone-911cead7/.git
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-911cead7/.git'
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-06-29T01_00_56_107Z-debug.log

Same message/

**Comment by lukasroegner** [comment]
This issue occurred due to a git-based dependency. The latest version 0.8.7 doesn't have that dependency, so installation should succeed.
