### ISSUE TITLE
[AppleTvPlatform] Error while sending heartbeat: undefined

### ISSUE THREAD

**Issue by johnlietzke** [lukasroegner/homebridge-apple-tv-remote#53]
TVOS 14 - experiencing this [AppleTvPlatform] [Apple TV] Error while sending heartbeat: undefined.  I know it is early in the developer phase.  It is happening on multiple Apple TV's but not everyone of them.

**Comment by MsCopernic** [comment]
I'm experiencing the same problem, and as you say, not with all my Apple TV devices. I'm also using tvOS 14

**Comment by johnlietzke** [comment]
I communicated another problem to the plug in developer a few months back and he was top notch.

**Comment by mkrus** [comment]
I downgraded to tvOS 13 and still get the issue

**Comment by johnlietzke** [comment]
Interesting.  

Do you have more than one Apple TV?  If so did, you downgrade them all?  It would be helpful to know if it is a hub issue with the Apple TV.  My initial thought was that the hub dynamics changed with TVOS 14 and therefore it was impacting then manner in which the Apple TV was communicating status. 

 I am going to check if the IP remains persistent or if it dynamically finds an IP when it reconnects to the network on restart or sleep.  If it dynamically finds an IP on reconnect setting a static IP may be a work around.

I am guess that the network connectivity while sleeping is not the issue.  As even when connected and repaired the Apple TV can not be turned off from Siri.

**Comment by lukasroegner** [comment]
Please use #46 for issues regarding the heartbeat error. It only informs you that the socket connection to the AppleTV has ended (cause is still unknown, it does not occur for all users).
