### ISSUE TITLE
Heartbeat error ??

### ISSUE THREAD

**Issue by MsCopernic** [lukasroegner/homebridge-apple-tv-remote#54]
Hi, I'm running this plugin in a Raspberry PI, was working perfectly before installing the latest version, I'm using homebridge-broadlink-rm v3.6.22 and homebridge-apple-tv-remote v0.8.7, the error message is the following one.

[AppleTV xxxxxxx] Error while sending heartbeat: undefined

If you need any additional information, please let me know.

Best regards

**Comment by mkrus** [comment]
I'm getting the same

**Comment by johnlietzke** [comment]
Are you on TVOS 14?  I noticed the problem shortly after updating to TVOS 14. It may just be a coincidence.

**Comment by lukasroegner** [comment]
Please use #46 for issues regarding the heartbeat error. It only informs you that the socket connection to the AppleTV has ended (cause is still unknown, it does not occur for all users).
