### ISSUE TITLE
Recommendation for specific iTunes station

### ISSUE THREAD

**Issue by whreams** [lukasroegner/homebridge-apple-tv-remote#56]
Hi guys, 
Trying to see what the recommendation is for choosing a specific iTunes Radio station on the Apple TV.  I could do the traditional remote step calls (left, right, down, down...) or could I the API in some way?  If the API is the answer, could an example be shared that shows how to do this?  Thanks!

**Comment by lukasroegner** [comment]
The API that this plugin uses is only for virtual remote inputs. There is no way to change settings of apps running on the Apple TV. 

I would recommend to post questions like that in smart home forums. There, you might get suggestions based on other APIs/systems. My personal suggestion: if you find a way to choose the radio station via Siri Shortcut, you could use the automation server feature of the iOS app Pushcut.

**Comment by whreams** [comment]
Thank you Lukas for your response. 
I tried to find a location to post such a query but didn’t find a “general” section on your GitHub page.  I’m using pushcarts in conjunction with HTTP Switch.  The shortcuts app has some shortcomings that I’ve noticed over the few months.  I was trying to see if others had found alternatives in choosing such a media source.  I’ve posed the same query in the HB-Discord with hopes more ideas come in.  Guess I’ll continue to wrestle with the shortcut issues until then.  Thanks again, and nice work on the plugin. 
Thanks! - Bill
