### ISSUE TITLE
After switching from git to npm version error message (The requested platform 'AppleTvPlatform' was not registered by any plugin.)

### ISSUE THREAD

**Issue by Nastras** [lukasroegner/homebridge-apple-tv-remote#6]
Hello Lukas,

i just switched from the git version to the npm version after uninstall with sudo npm uninstall -g homebridge-appletv and then sudo npm install -g --unsafe-perm homebridge-harmony@latest -g.

 After that I have this error when starting the plugin:

<img width="1058" alt="Bildschirmfoto 2020-01-25 um 15 45 43" src="https://user-images.githubusercontent.com/27686185/73122947-ae44c280-3f8a-11ea-80b9-3032ac0411d3.png">

Do you have any ideas?

Greetings Nastra

**Comment by lukasroegner** [comment]
See #5, package is now called `homebridge-apple-tv-remote`.

**Comment by Nastras** [comment]
👍👍👍👌👌 Thx .-)
