### ISSUE TITLE
Play Pause Switch isn’t updating since tvOS 14

### ISSUE THREAD

**Issue by try-and-error-and-repeat** [lukasroegner/homebridge-apple-tv-remote#60]
Since the update to tvOS14 the play pause switch isn’t changing when I pause or play on an app like Netflix or Amazon prime. 
Before tvOS 14 it was working fine. 
I already restarted Homebridge/ my RaspberryPI/ my Apple TV 4K - nothing helped. I also paired again. 
When I press the button manually in the home app the video play/pauses. But if I change with remote there is no update in the home app

**Comment by lukasroegner** [comment]
New version 0.9.0 on NPM. It seems that with iOS 14 the underlying library (`node-appletv-x`) does not handle the queue state correctly. The library is now archived, which means not maintained anymore.

I figured out a way to get the playback state back working.

**Comment by RaymondMouthaan** [comment]
I will test it right away 👍

**Comment by try-and-error-and-repeat** [comment]
For me it's sometimes working sometimes not. Means that the switch in HomeKit isn't updating right. Sometimes on means Pause sometimes play. I restarted my Apple TV and also homebridge. 

Any ideas?

**Comment by lukasroegner** [comment]
@try-and-error-and-repeat Some users also experience issues with this plugin, reliability seems to change depending on host system and network configuration, see #46. Also, some apps don't report their playback state correctly, I always test with the Apple TV app and Netflix.

I close this issue for now as the recent changes fixed the actual issue of not getting any messages from the Apple TV.

**Comment by try-and-error-and-repeat** [comment]
I think I know the problem. The Update works fine with Plex, Amazon Prime, Disney+, Apple TV+. I think the problem is the Autoplay function on Netflix then the switch is updated wrong sometimes. Maybe this helps for further updates. I've checked it in debug mode.
