### ISSUE TITLE
[Feature Request] Add simple HTTP control commandsupport

### ISSUE THREAD

**Issue by capdav** [lukasroegner/homebridge-apple-tv-remote#61]
Hi,

First of all, thanks a lot for your great work!
Finally a solution that I can use to control my ATV using HTTP requests. 
Unfortunately, my processor only support HTTP get request to send command. 
Do you think it possible to ask this feature?

Thanks

**Comment by lukasroegner** [comment]
Hi @capdav, I don't really want to add a GET endpoint for actions that control the Apple TV (REST principles). Which processor are you using?

**Comment by capdav** [comment]
Hi Lukas,
Indeed I understand, but my feature request is not correct (I rename it)
My processor (ProControl) only allows me to send http request. There is no REST support at all. So it’s simple http get where the command/control could be set as parameter.

**Comment by flinke-flasche** [comment]
I would also like to have HTTP control for my Home Cinema remote control.

**Comment by lukasroegner** [comment]
Latest version contains a simple HTTP GET endpoint to switch on/off and play/pause, see **API - Send Commands (Simple)** in the README.
