### ISSUE TITLE
[bug report] power state switching on>off>on when turning in Apple TV

### ISSUE THREAD

**Issue by Post404** [lukasroegner/homebridge-apple-tv-remote#63]
When turning on the Apple TV, the switch for the power state switches to on, then to off and back to on within a second.

This essentially triggers both the automations for turning on and for turning off.
I never noticed this or had problems with automations based on the power state as it always worked anyway.
But now that I added a IR Beamer I did notice.
Since the switching happens so fast the IR Beamer is beaming the signals for turning on and off at almost the same time and not all of them come through.

I think this is related to the stability issues, but I haven't seen anyone talk about this before.

**Comment by lukasroegner** [comment]
Do you have any suggestions on how to enhance the behavior? Dampening for on/off data coming from the Apple TV?

**Comment by Post404** [comment]
Thanks for your quick response.
I don't know exactly what you mean with dampening.

Since the power state doesn't change in quick succession I would say you could get away by locking the power state for 1 or 2 seconds after it changes. So nothing from "power off" automations get triggered. After that it is open for changing the state again.

**Comment by bleeps** [comment]
I have the same issue here and as you have suggested locking the power state for 1-2 seconds would solve issues for automations based on power states

**Comment by lukasroegner** [comment]
Please check out the latest version, which includes a fix for unstable on/off and play/pause states!
