### ISSUE TITLE
How to acquire API Token?

### ISSUE THREAD

**Issue by holzerseb** [lukasroegner/homebridge-apple-tv-remote#72]
The documentation unfortunately does not state, how one can get the API Token. Is it the same as the 'Credentials' after pairing your Apple TV? From what I understood in the documentation, they are not the same tokens/credentials.

**Comment by lukasroegner** [comment]
If you want the plugin to expose an HTTP API, you just have to define the API token yourself. If you're not planning to use the HTTP API, just leave it blank.

**Comment by fahad00x** [comment]
Hi 
I did not understand how I can write API token .. can you Clarify it please

**Comment by lukasroegner** [comment]
The API token can be anything you want, is it like a password that you choose.

**Comment by fahad00x** [comment]
Oh , ok thank you

I have another question please
In API
http://<YOUR-HOST-IP-ADDRESS>:<apiPort>

The host IP adress is Apple TV IP or  raspberry pi IP?

And the apiPort is the port for raspberry pi ?

**Comment by fahad00x** [comment]
http://<YOUR-HOST-IP-ADDRESS>:<apiPort>

**Comment by fahad00x** [comment]
http:// <YOUR-HOST-IP-ADDRESS>:<apiPort>

**Comment by fahad00x** [comment]
http:// YOUR-HOST-IP-ADDRESS : apiPort
