### ISSUE TITLE
Problem when using AppTv "physical remote"

### ISSUE THREAD

**Issue by kitsen13** [lukasroegner/homebridge-apple-tv-remote#74]
Hello,

I have noticed a problem on the "virtual TV on/off homebridge switch".

To repoduce : 
- 1 - Switch ON Apple Tv with the "virtual TV on/off homebridge switch"
- 2 - Switch OFF Apple Tv with the AppTv "physical remote"
- 3 - Problem n° 1 =  "virtual TV on/off homebridge switch" stayed to the state TRUE with an Apple Tv state to OFF
- 4 - Problem n° 2 = if you traying to put to FALSE your "virtual TV on/off homebridge switch", the Apple Tv switches ON...
- 5 - Now the Apple Tv state is ON, if you traying to put to TRUE your "virtual TV on/off homebridge switch", no action -> OK

When I use the AppTv "physical remote", i desync the  "virtual TV on/off homebridge switch".

Regards

**Comment by distantnative** [comment]
I seem to have the same issue.
The plugin switch doesn't turn the Apple TV off anymore, though displays the state as off. If I hit the switch again to turn it on, the top menu button is actually registered by the Apple TV. But not the off action.

**Comment by lukasroegner** [comment]
I cannot reproduce your issue. Please provide detailed logs (start Homebridge with parameter `-D` so that we can correlate the log entries with your input on the Apple TV remote.

**Comment by kevinjohncutler** [comment]
I also have a similar issue. More simply, the plugin was synced with the TV state when first installed, but now it is only recognized much later if at all (e.g. the TV state is on only when I have started playing something, not when it actually wakes from sleep).

**Comment by lukasroegner** [comment]
Could be related to #77 or #46, without detailed logs, it is impossible for me to check on your issue.
