### ISSUE TITLE
Unexpected "turned off" reporting during the Apple TV is still turned on

### ISSUE THREAD

**Issue by gklka** [lukasroegner/homebridge-apple-tv-remote#75]
My goal is to use this plugin to simultaneously turn on or off a smart plug (belonging to my amplifier) along with the Apple TV. I've set up the automation for it and works fine most of the time, but unfortunately every few hours it drops a mistake. I hear when the amplifier turns on or off so I can tell that many times it turns it on despite the Apple TV is off, and many times I am watching a movie on the TV and the automation turns off the smart plug for 10-15 sec, because it thinks the Apple TV is off. So what can I do to have a more reliable status report of my Apple TV?

**Comment by ashneedham** [comment]
I too have experienced this. I have a Logitech Harmony activity created to turn on / off my amp but incorrect messages from the ATV switch cause the amp to turn on and off at inappropriate times.
I've watched the status of the ATV switch in Homebridge accessories tab and can see the action clearly.

**Comment by lukasroegner** [comment]
As already stated, this plugin is not stable, the stability issues are tracked in #46. I would not use it in a production environment yet, as is it not reliable enough to be used within automations.
