### ISSUE TITLE
Not supported accessory

### ISSUE THREAD

**Issue by maxime-killinger** [lukasroegner/homebridge-apple-tv-remote#78]
I added the TV accessory from the plug-in, it’s working well. But from then I have an additional accessory not supported on the Home app that I can’t remove. 
![24DF4BBB-AB84-4711-AC9C-A15774A1DCE7](https://user-images.githubusercontent.com/15786158/98041269-f1896700-1e21-11eb-9b62-6840b7967f9a.jpeg)
I already tried to remove the accessory, but it come back even after clearing the cache. 
I’m running the last version of the plug-in with an Apple TV on TvOS 14.

**Comment by maxphour** [comment]
Hey @maxime-killinger, 
I don't know a way to remove it either, but I discovered that you can at least move it if you enable the switch in the config. 
By the way: How did you manage to add the TV accessory? If I try to add it and enter pin 8x zero, I'm getting an error. It says something like: "device is not ready for connection"

**Comment by lukasroegner** [comment]
@maxime-killinger Can you please post your config?

**Comment by maxime-killinger** [comment]
@lukasroegner there is my config for the plugin
```
        {
            "name": "Apple TV Platform",
            "devices": [
                {
                    "name": "Apple TV",
                    "credentials": "26963CF6-B070-4ABC-B7DD-8374E3B45828:34363337663436332d633637392d343665622d396435642d373132393632616438313861:64373833333335612d363430332d343338662d613236622d336632643439386630643935:3139da1c6163c9530f3b0ae7cdf14354256eac1909c3668faf4c5418850d550e:64fa05d32ec63006f52113b31121f057bb30d1abb378eb594c1634096c596b05",
                    "isOnOffSwitchEnabled": false,
                    "isOnOffTvEnabled": true,
                    "onOffTvName": "Apple TV",
                    "isPlayPauseSwitchEnabled": false
                }
            ],
            "platform": "AppleTvPlatform"
        }
```

@maxphour I didn't have your problem, I just used my Homebridge code to add the tv without any problem

**Comment by lukasroegner** [comment]
Looks fine. Please try to remove the external TV from HomeKit, set the value for `onOffTvName` in the config, and re-add it again.

**Comment by maxime-killinger** [comment]
Done. And the unsupported accessory is still here. I have also cleaned the cache, nothing change.

**Comment by Reapzy** [comment]
Good evening! I've got the exact same issue, the "switch" option works fine

**Comment by lukasroegner** [comment]
Open the details view of the unsupported accessory and scroll down. Does it say "Remove device" or is there a "Bridge" button?

**Comment by Reapzy** [comment]
Good evening!
There is a "bridge" button
![image](https://user-images.githubusercontent.com/38317538/101521885-b4ffdc80-3986-11eb-84a9-1e6d4e7b1be8.jpeg)

**Comment by jjuuzzii** [comment]
same here

**Comment by idominiki** [comment]
Hey Lukas. Auch ich habe das selbe Problem. 

Beste Grüße und schöne Feiertage!

**Comment by jdebardi** [comment]
Did anyone manage to solve this? I just install this plugin today and have the same issue.

My config;
```
{
            "name": "Apple TV Platform",
            "devices": [
                {
                    "name": "Lounge Apple TV",
                    "credentials": "<removed>",
                    "isOnOffTvEnabled": true
                }
            ],
            "isApiEnabled": true,
            "apiToken": "homebridgeappletv",
            "platform": "AppleTvPlatform"
        }
```

**Comment by jdebardi** [comment]
I worked out the issue.

If you ONLY enable the extra TV Accessory the code still adds a stub 'normal' accessory but never associates any switches with it (as you didn't as it to).

The quick fix I did was to add an if statement in apple-tv-controller.js around the stub accessory statement so it only does it if any of the child switches are to be created;
```
if (deviceConfiguration.isOnOffSwitchEnabled || deviceConfiguration.isPlayPauseSwitchEnabled || (deviceConfiguration.appPlayPauseSwitches && deviceConfiguration.appPlayPauseSwitches.length > 0) || (deviceConfiguration.commandSwitches && deviceConfiguration.commandSwitches.length > 0) ) {
            var accessory = platform.useAccessory(deviceConfiguration.name, client.id);
            accessory.setInformation({
                manufacturer: 'Apple',
                model: 'Apple TV',
                serialNumber: client.id,
                firmwareRevision: null,
                hardwareRevision: null
            });
}
```

**Comment by maxime-killinger** [comment]
> I worked out the issue.
> 
> 
> 
> If you ONLY enable the extra TV Accessory the code still adds a stub 'normal' accessory but never associates any switches with it (as you didn't as it to).
> 
> 
> 
> The quick fix I did was to add an if statement in apple-tv-controller.js around the stub accessory statement so it only does it if any of the child switches are to be created;
> 
> ```
> 
> if (deviceConfiguration.isOnOffSwitchEnabled || deviceConfiguration.isPlayPauseSwitchEnabled || (deviceConfiguration.appPlayPauseSwitches && deviceConfiguration.appPlayPauseSwitches.length > 0) || (deviceConfiguration.commandSwitches && deviceConfiguration.commandSwitches.length > 0) ) {
> 
>             var accessory = platform.useAccessory(deviceConfiguration.name, client.id);
> 
>             accessory.setInformation({
> 
>                 manufacturer: 'Apple',
> 
>                 model: 'Apple TV',
> 
>                 serialNumber: client.id,
> 
>                 firmwareRevision: null,
> 
>                 hardwareRevision: null
> 
>             });
> 
> }
> 
> ```
> 
> 
> 
> I have created pull request #90 for this so hopefully will get merged.

@lukasroegne any news about this fix ?

**Comment by lukasroegner** [comment]
Sorry, I overlooked the PR. It is now merged, new version on NPM.

**Comment by maxime-killinger** [comment]
@lukasroegner @jdebardi thank's, it's fix
