### ISSUE TITLE
node-appletv-x close connection

### ISSUE THREAD

**Issue by dragouf** [lukasroegner/homebridge-apple-tv-remote#80]
sorry I can't open any issue on node-appletv-x but I have a question related to it.

is there any reason why on `closeConnection` connection just call .end() on socket but not destroy ? 

because of that my script never end and I have to do `device.connection.socket.destroy();`

is it a correct way to end the script ? How it is expected to be use in a script ?

**Comment by lukasroegner** [comment]
Hi @dragouf, the `node-appletv-x` doesn't seem to be actively developed anymore. I haven't worked through the whole source code of the package, yet, so I can't answer your question.
