### ISSUE TITLE
Can this code be used in 'apple shortcuts' as script to control volumeup & volumedown on the Apple TV? could you post or reply an example. cheers

### ISSUE THREAD

**Issue by mrfibreoptic** [lukasroegner/homebridge-apple-tv-remote#85]
Can this code be used in 'apple shortcuts' as script to control volumeup & volumedown on the Apple TV? could you post or reply an example. cheers

**Comment by lukasroegner** [comment]
You can use the plugin HTTP API to send a virtual volume-up or volume-down to the Apple TV. This, however, works only if you can control the volume directly on the Apple TV (infrared via Siri Remote is not supported).

```
POST http://<YOUR-HOST-IP-ADDRESS>:<apiPort>/<UNIQUE-NAME>

{
  "commands": [{ "key": "volumeup" }]
}
```

or

```
POST http://<YOUR-HOST-IP-ADDRESS>:<apiPort>/<UNIQUE-NAME>

{
  "commands": [{ "key": "volumedown" }]
}
```

**Comment by mrfibreoptic** [comment]
![9000F5CD-D88D-40D2-A737-A804E80CC651](https://user-images.githubusercontent.com/64764878/105222186-01ae1880-5bbf-11eb-9ee3-86b0fa3982f0.jpeg)

where do I put the command?

**Comment by lukasroegner** [comment]
1. Remove the "<" and ">" characters from the URL
2. key = commands, value has to be of type Array
3. Add a single entry to the Array, type Dictionary
4. Add a new property to the Dictionary, key = key, value = volumeup

**Comment by mrfibreoptic** [comment]
any chance you could create a volume up shortcut that you could share so i can understand better? apologies for being a pain
