### ISSUE TITLE
Open a specific app

### ISSUE THREAD

**Issue by peter99330** [lukasroegner/homebridge-apple-tv-remote#86]
Is it possible to open a specific app through this plugin? In the README there is section with "bundle identifiers", but I cannot seem to find any way to use them.

It should be possible to do this, as the shortcuts app can do it from any iPhone. If there is any help needed (e.g. capturing traffic while opening an app through a shortcut) I will gladly try to help.

Thanks in advance!

**Comment by klomic** [comment]
Same problem by me, hope we get any respond soon.
Thanks for help

**Comment by lukasroegner** [comment]
This is not possible. You can only develop a chain of key commands (go to home screen -> navigate to the app on the home screen -> click select) to open the app and use a command switch or the API.
