### ISSUE TITLE
Send wrong BundleID

### ISSUE THREAD

**Issue by Chrigigi** [lukasroegner/homebridge-apple-tv-remote#91]
Ich have two button for Netflix and YouTube
<img width="437" alt="Bildschirmfoto 2021-02-14 um 09 35 01" src="https://user-images.githubusercontent.com/78798738/107872133-3b193180-6ea8-11eb-8603-291f468420c4.png">

no matter which button i press, it always transmits "com.apple.TVMusic"
<img width="991" alt="Bildschirmfoto 2021-02-14 um 09 39 53" src="https://user-images.githubusercontent.com/78798738/107872202-bd095a80-6ea8-11eb-9da4-c2ba449fad76.png">

**Comment by lukasroegner** [comment]
Please go through the README again: the plugin does not send the bundle ID, it can just listen for the bundle ID. In your case, the Apple TV states that the current source for playback (either playing or pauses) is the Apple Music app.
