### ISSUE TITLE
How to configure iptables?

### ISSUE THREAD

**Issue by meltinsands** [lukasroegner/homebridge-apple-tv-remote#99]
I use iptables to control the traffic, but the Apple TV remote only works successful, if the firewall is completely switched off. Could you please let me know which port (in/out + tcp/udp) is used to communicate with Apple TV. Sorry, but so far I could not solve this issue. I do not use the API.
Thank you!

**Comment by lukasroegner** [comment]
I'm afraid you'll have to figure it out yourself. The plugin is just a "wrapper" around the [node-appletv-x](https://github.com/stickpin/node-appletv-x) library. I would have suggested to file an issue there, however, the library has been archived by now and is no longer maintained.
